spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:28081/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
server:
  port: 28085
feign:
  hystrix:
    enabled: true